/* Generated By:JavaCC: Do not edit this line. BibTeXParserConstants.java */
package org.jbibtex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BibTeXParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INLINE_COMMENT = 2;
  /** RegularExpression Id. */
  int TEXT = 4;
  /** RegularExpression Id. */
  int AT = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int EQUALS = 12;
  /** RegularExpression Id. */
  int HASH = 13;
  /** RegularExpression Id. */
  int LBRACE = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int QUOTE = 16;
  /** RegularExpression Id. */
  int RBRACE = 17;
  /** RegularExpression Id. */
  int RPAREN = 18;
  /** RegularExpression Id. */
  int COMMENT = 19;
  /** RegularExpression Id. */
  int INCLUDE = 20;
  /** RegularExpression Id. */
  int PREAMBLE = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int NAME = 23;
  /** RegularExpression Id. */
  int DIGITS = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_INLINE_COMMENT = 1;
  /** Lexical state. */
  int IN_LITERAL = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"%\"",
    "<INLINE_COMMENT>",
    "<token of kind 3>",
    "<TEXT>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\"",
    "\" \"",
    "\"@\"",
    "\",\"",
    "\"=\"",
    "\"#\"",
    "\"{\"",
    "\"(\"",
    "\"\\\"\"",
    "\"}\"",
    "\")\"",
    "<COMMENT>",
    "<INCLUDE>",
    "<PREAMBLE>",
    "<STRING>",
    "<NAME>",
    "<DIGITS>",
  };

}
