/* Generated By:JavaCC: Do not edit this line. LaTeXParserConstants.java */
package org.jbibtex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LaTeXParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BACKSLASH = 1;
  /** RegularExpression Id. */
  int LBRACE = 2;
  /** RegularExpression Id. */
  int RBRACE = 3;
  /** RegularExpression Id. */
  int SPECIAL = 4;
  /** RegularExpression Id. */
  int NON_SPECIAL = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int WHITESPACE = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\\\"",
    "\"{\"",
    "\"}\"",
    "<SPECIAL>",
    "<NON_SPECIAL>",
    "<LETTER>",
    "<NUMBER>",
    "<WHITESPACE>",
  };

}
